In [13]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [14]:
user_rating = pd.read_csv(r"C:\Users\PREM MOTGHARE\Desktop\introduction to aiml by infosys\python\Data\user_rating.csv")
user_rating.head()

  userID  placeID  food_rating  service_rating
0  U1077   135085            2               2
1  U1077   135038            2               1
2  U1077   132825            2               2
3  U1077   135060            2               2
4  U1068   135104            1               2

In [16]:
#Importing Data from Spread Sheets - consumer_survey
consumer_survey = pd.read_excel(r"C:\Users\PREM MOTGHARE\Desktop\introduction to aiml by infosys\python\Data\consumer_survey.xlsx")
consumer_survey.head()

,gender,smoker,drink_level,dress_preference,ambience,transport,marital_status,interest,personality,religion,activity,income,FRVPM,AERPM
0,male,False,abstemious,informal,family,on foot,single,variety,thrifty-protector,none,student,medium,12,2976
1,female,False,abstemious,informal,family,public,single,technology,hunter-ostentatious,Catholic,student,low,12,3648
2,female,False,social drinker,formal,family,public,single,none,hard-worker,Catholic,student,low,3,1461
3,male,False,abstemious,informal,family,public,single,variety,hard-worker,none,professional,medium,18,4014
4,female,False,abstemious,no preference,family,public,single,none,thrifty-protector,Catholic,student,medium,15,3045

In [18]:
#Importing Data from Spread Sheets - restaurant_parking
restaurant_parking = pd.read_excel(r"C:\Users\PREM MOTGHARE\Desktop\introduction to aiml by infosys\python\Data\restaurant_parking.xlsx")
restaurant_parking.head()

   placeID parking_lot
0   135111      public
1   135110        none
2   135109        none
3   135108        none
4   135107        none

In [20]:
#Importing Data from Spread Sheets - dining_preferences
dining_preferences = pd.read_excel(r"C:\Users\PREM MOTGHARE\Desktop\introduction to aiml by infosys\python\Data\dining_preferences.xlsx")
dining_preferences.head()

   Year  Dine_In  Home_Delivery
0  1990     5649              0
1  1991     5539              0
2  1992     5760            104
3  1993     6509             76
4  1994     6982            156

In [22]:
#Importing Data from Spread Sheets - restaurant cuisine
restaurant_cuisine = pd.read_excel(r"C:\Users\PREM MOTGHARE\Desktop\introduction to aiml by infosys\python\Data\restaurant_cuisine.xlsx")
restaurant_cuisine.head()

   placeID       Rcuisine
0   132001  Dutch-Belgian
1   132002        Seafood
2   132003  International
3   132004        Seafood
4   132005         French